### PR TITLE
Task/javascript generator

### PR DESCRIPTION
**Pull request by Vektrat**
Includes and finalizes the code generation pipeline for JavaScript, missing:

- Automatic copying of `JavaScriptUtils.js` from support files to the generated output directory (needs manual copying now)
- `getSize()` function for the transactions ( #15 )

### CODE REVIEW

**Comment by Vektrat** [comment]
1. can include comments, didn't give it much importance, preferred to have a working version asap
2. Licenses are missing yes, this was added later than i wrote the initial version and is still pending
3. Considered ES6, but this is adding restrictions to the output code, this is supposed to be JavaScript code that can be put into other projects (such as SDK) as a supporting tool, so if we output (for example) as ES6, we will be imposing ES6 environment to whatever project wants to use catbuffer (this is related to the following comment)

About JS/TS... I think it is a mistake to take output code and migrate into TS... we should expect updates to the catbuffer schemas anytime, and this would be a pain, afaik this is supposed to be a tool to promote copypasting the output files directly for use into the project - TS is compatible with JS, and i think those should stay like so

**Comment by evias** [comment]
I second @Vektrat here, catbuffer generated code should be treated like swagger generated code and not modified when added to the SDK.

As discussed in private, @rg911, what you can do is to add ".d.ts" interfaces.

**Comment by rg911** [comment]
> I second @Vektrat here, catbuffer generated code should be treated like swagger generated code and not modified when added to the SDK.
> 
> As discussed in private, @rg911, what you can do is to add ".d.ts" interfaces.

I have already made breakthroughs for the Typescript generator. Will leave it for future retro. But for now, yeah, have to create the definition files and copy these js files to the dist folder.

**Comment by fboucquez** [comment]
@rg911 @Wayonb should we remove this one? This one has been superseded by the ts generator and it's not up to date with f2. I believe you can compile ts down to js if the potential client is not using typescript.

**Pull request closed without merging**
